"""empty message

Revision ID: 52341488d1c9
Revises: 8f9538fe1bcb
Create Date: 2022-08-17 18:23:31.901547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52341488d1c9'
down_revision = '8f9538fe1bcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=50), nullable=False))
    op.drop_constraint('user_usermane_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'usermane')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('usermane', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_usermane_key', 'user', ['usermane'])
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
